if(WIN32)
	if(MSVC)
		FIND_LIBRARY(IRRLICHT_LIBRARY NAMES Irrlicht.lib
			PATHS
			${CMAKE_CURRENT_SOURCE_DIR}/cmake/lib/Win64		)
	endif()
elseif(WIN64)
	if(MSVC)
		FIND_LIBRARY(IRRLICHT_LIBRARY NAMES Irrlicht.lib
			PATHS
			${CMAKE_CURRENT_SOURCE_DIR}/cmake/lib/Win64
		)
	endif()
else()
	FIND_LIBRARY(IRRLICHT_LIBRARY NAMES libIrrlicht.a
		HINTS
		${CMAKE_CURRENT_SOURCE_DIR}/cmake/lib/Unix
		NO_DEFAULT_PATH
		NO_SYSTEM_ENVIRONMENT_PATH
		# /usr/local/lib
	)
endif()

FIND_PATH(IRRLICHT_INCLUDE_DIR NAMES irrlicht.h
	PATHS
	${CMAKE_CURRENT_SOURCE_DIR}/cmake/lib/irrlicht-includes
	# /usr/irrlicht-includes
)

MESSAGE(STATUS "IRRLICHT_INCLUDE_DIR = ${IRRLICHT_INCLUDE_DIR}")
MESSAGE(STATUS "IRRLICHT_LIBRARY = ${IRRLICHT_LIBRARY}")

# On windows, find the dll for installation
if(WIN32)
	if(MSVC)
		FIND_FILE(IRRLICHT_DLL NAMES Irrlicht.dll
			PATHS
			"${CMAKE_CURRENT_SOURCE_DIR}/lib/Win64"
		)
	endif()
	MESSAGE(STATUS "*** IRRLICHT_DLL = ${IRRLICHT_DLL} ***")
elseif(WIN64)
	if(MSVC)
		FIND_FILE(IRRLICHT_DLL NAMES Irrlicht.dll
			PATHS
			"${CMAKE_CURRENT_SOURCE_DIR}/lib/Win64"
		)
 	endif()
	MESSAGE(STATUS "*** IRRLICHT_DLL = ${IRRLICHT_DLL} ***")
endif()

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(IRRLICHT DEFAULT_MSG IRRLICHT_LIBRARY IRRLICHT_INCLUDE_DIR)

IF(IRRLICHT_FOUND)
  SET(IRRLICHT_LIBRARIES ${IRRLICHT_LIBRARY})
ELSE(IRRLICHT_FOUND)
  SET(IRRLICHT_LIBRARIES)
ENDIF(IRRLICHT_FOUND)

MARK_AS_ADVANCED(IRRLICHT_LIBRARY IRRLICHT_INCLUDE_DIR IRRLICHT_DLL)